### ISSUE TITLE
Mechanical scripting API reference

### ISSUE THREAD

**Issue by koubaa** [ansys/pymechanical#176]
The API reference guide for pymechanical only includes the apis defined by pymechanical, and not the ones that come from the mechanical scripting API.  This is unfortunate, since most of the code users have to write is using the scripting API.

We already have an automated system to generate the API reference guide in docbook format in our product help, but for PyMechanical we need to generate sphinx doc for the API reference guide.

**Comment by klmcadams** [comment]
Closed by `ansys-mechanical-stubs` repo creation & documentation on the dev portal
