### ISSUE TITLE
Include a section to specify limitations for Mechanical Scripting Compatibilities in Embedded Instance

### ISSUE THREAD

**Issue by rajesh1359** [ansys/pymechanical#194]
### Description of the modifications

There are few common APIs which currently does not work in Embedding session, for example **Transaction** method.

It would be good to mention that APIs will behave as they would behave in Mechanical batch mode.

**Comment by koubaa** [comment]
@rajesh1359 could you list the ones you encounter here?  I think we have to support Transaction in embedding mode (and it should be straightforward to do that)
