### ISSUE TITLE
remove lock file when the Application object is cleaned up

### ISSUE THREAD

**Issue by koubaa** [ansys/pymechanical#246]
When opening a mechdb file in pymechanical, at the end of the script, the lock file still exists on disk. This prevents opening the mechdb again without manually deleting the lock file.

When the application exits, the lock file should be removed.  This might be possible to support simply by adding an app.close() to the atexit handler.

**Comment by DragomirDeltchev** [comment]
I believe we need app.close() to:

- close the instance 
- delete the lock file
