### ISSUE TITLE
[Embedding] Bug running embedded mechanical in python 3.10.11

### ISSUE THREAD

**Issue by waltersma** [ansys/pymechanical#255]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

See following error when embedding mechanical in python:

Exception has occurred: SEHException
 (0x80004005): External component has thrown an exception.
  File "test.py", line 7, in <module>
    with App() as app:

### 📝 Steps to reproduce

- create venv with python 3.10.11
- pip install ansys.mechanical.core
- embed mechanical in python:

from ansys.mechanical.core import App

with App() as app:
    print(app)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23r2 pre release

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-mechanical==0.1.0
ansys-api-platform-instancemanagement==1.0.0b3
ansys-mechanical-core==0.8.0
ansys-platform-instancemanagement==1.1.1
ansys-pythonnet==3.1.0rc1
appdirs==1.4.4
cffi==1.15.1
clr-loader==0.2.5
colorama==0.4.6
googleapis-common-protos==1.59.0
grpcio==1.54.2
importlib-metadata==6.6.0
protobuf==3.20.3
protoc-gen-swagger==0.1.0
pycparser==2.21
tqdm==4.65.0
zipp==3.15.0
```

**Comment by koubaa** [comment]
Upgrade to pymechanical version 0.9.

There you can set up logging, as documented here:

https://mechanical.docs.pyansys.com/version/stable/user_guide_embedding/logging.html

I need to see the log at the DEBUG level in order to know why it failed to start up

**Comment by RemishR** [comment]
I am getting an error while I am trying to embed an instance of mechanical in python using pymechanical. I don't know what is the issue. Could you please check?

I have installed **ansys-mechanical-core                 0.8.0**
Ansys Version 2023 R1
python 3.10.11



![Input](https://github.com/ansys/pymechanical/assets/136232547/b295d596-e88e-47a4-9a9d-deb9c5d0a8f6)
![output](https://github.com/ansys/pymechanical/assets/136232547/84211c81-7c5f-43c7-8666-5d64bc4754be)

**Comment by koubaa** [comment]
@RemishR please file a new issue, don't add an unrelated issue to an existing one.

**Comment by koubaa** [comment]
I came up with a workaround for walter... but need to spend more time to find out the root cause and fix it
