### ISSUE TITLE
Bug located in embedding/linux/tracemap

### ISSUE THREAD

**Issue by rs-bh-n** [ansys/pymechanical#261]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When we set the external data identifier for an imported tracemap, we get an error on linux machine .

### 📝 Steps to reproduce

zip attached . use the attached python file along with mechdat .
windows - runs fine
linux (centos 7.9.2009) - results in error

![image](https://github.com/ansys/pymechanical/assets/96760708/1d275ca0-3b28-46de-86b9-0834d73acc04)

[generic_232_linux.zip](https://github.com/ansys/pymechanical/files/11624396/generic_232_linux.zip)

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

Ansys 232 may 30th build

![image](https://github.com/ansys/pymechanical/assets/96760708/0d104c30-91d5-4416-aab9-2b7742b4cee1)

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-mechanical==0.1.0
ansys-api-platform-instancemanagement==1.0.0b3
ansys-mechanical-core==0.8.0
ansys-platform-instancemanagement==1.1.1
ansys-pythonnet==3.1.0rc1
appdirs==1.4.4
cffi==1.15.1
clr-loader==0.2.5
googleapis-common-protos==1.59.0
grpcio==1.54.2
importlib-metadata==6.6.0
numpy==1.24.3
pandas==2.0.1
Pint==0.22
protobuf==3.20.3
protoc-gen-swagger==0.1.0
pycparser==2.21
python-dateutil==2.8.2
pytz==2023.3
six==1.16.0
tqdm==4.65.0
typing_extensions==4.6.2
tzdata==2023.3
zipp==3.15.0
```

**Comment by rs-bh-n** [comment]
Hi @koubaa , Can you look into this ? Any workaround for Linux would be great.

**Comment by koubaa** [comment]
This has been fixed in the backend dev version of Mechanical.  So with 2024 R1, this script will work.
