### ISSUE TITLE
[Imported Load External Data]: Expose API to apply imported pressure as "Direct" or "Surface Effect". Currently, we need to apply using InternalObject

### ISSUE THREAD

**Issue by vnamdeo** [ansys/pymechanical#318]
### 📝 Description of the feature

@samigithub2022 @koubaa :

Import loads using External Data, it's critical to apply imported loads as "Direct" in order to avoid Surface effect elements (SURF154) to use in FE model (will increase element counts) and sometime doesn't supported with certain analysis type (like in case of inverse solve). 

Currently,  using InternalObject to apply imported loads as "Direct" with the following command line,
Imported_Pressure.InternalObject.ExternalLoadAppliedBy = 1 ---> "Direct"

Imported_Pressure.InternalObject.ExternalLoadAppliedBy = 0 ---> "Surface Effect"

### 💡 Steps for implementing the feature

NA

### 🔗 Useful links and references

NA

**Comment by dipinknair** [comment]
Fixed in 24.1

**Comment by dipinknair** [comment]
Fixed in 24.1

**Comment by vnamdeo** [comment]
@dipinknair @koubaa : which release branch (241 or 242) this enhancement is going to be exposed via API ?
Please let me know. Thanks !
