### ISSUE TITLE
Change `app.close()` to `app.exit()`

### ISSUE THREAD

**Issue by koubaa** [ansys/pymechanical#365]
`exit` is a more standard term for exiting an application, while `close` refers usually to closing a document within an application.

**Comment by RobPasMue** [comment]
Watch out @koubaa - PyPIM uses this API explicitly

https://pypim.docs.pyansys.com/version/stable/api/_autosummary/ansys.platform.instancemanagement.Client.html#ansys.platform.instancemanagement.Client

**Comment by RobPasMue** [comment]
If you want to ensure compatibility, you might need to keep it

**Comment by koubaa** [comment]
@RobPasMue this is unrelated to PyPIM

**Comment by koubaa** [comment]
Looks like I already did this.. only thing left is to use the Exit API in 241+ instead of Close()
