### ISSUE TITLE
Missing documentation for Transaction

### ISSUE THREAD

**Issue by dipinknair** [ansys/pymechanical#402]
### Description of the modifications

Add documentation for Transaction 

### Useful links and references

https://mechanical.docs.pyansys.com/version/stable/user_guide_embedding/globals.html

_No response_

@koubaa

**Comment by koubaa** [comment]
documentation is indeed there, but Transaction is not working for embedded. 

Due to https://github.com/pythonnet/pythonnet/issues/79

This can be worked around pretty easily in pymechanical

**Comment by koubaa** [comment]
@dipinknair should we close this issue, now that we support transaction? Or is still missing documentation?

**Comment by dipinknair** [comment]
> @dipinknair should we close this issue, now that we support transaction? Or is still missing documentation?

Transaction has its API ref and added in globals section as well. I guess we can close this issue
