### ISSUE TITLE
pytest default for --ansys-version should be based on the what is installed

### ISSUE THREAD

**Issue by koubaa** [ansys/pymechanical#435]
On a docker container where 241 but not 232 is installed, pytest tries to use 232. It should default to 232 only if 232 is installed, otherwise use the installed version.

Additionally, if it can't find an installed version, the tests should error out at the collection phase, rather than trying to run the tests.

**Comment by RobPasMue** [comment]
You should have a fixture that does all this handling for you - @klmcadams @dipinknair please work on this. Use the ``ansys-tools-path`` package
