### ISSUE TITLE
re-enable the graphics export test

### ISSUE THREAD

**Issue by koubaa** [ansys/pymechanical#438]
It was disabled in order to get all the embedding tests running in the ci/cd

**Comment by klmcadams** [comment]
I added xvfb-run to the workflow file in #433, so it's running the image_export test as well now

https://github.com/ansys/pymechanical/actions/runs/6397457082/job/17365438692

**Comment by koubaa** [comment]
@klmcadams oops! I must been a few commits behind when I reviewed it. Sorry for the noise!

**Comment by klmcadams** [comment]
No worries!
