### ISSUE TITLE
Update to 241 

### ISSUE THREAD

**Issue by dipinknair** [ansys/pymechanical#565]
- [x] CI/CD https://github.com/ansys/pymechanical/pull/590
- [x] Docker ⏭️ #567 
- [x] Documentation https://github.com/ansys/pymechanical/pull/566
- [x] Examples 
    - [x] [remote](https://github.com/ansys/pymechanical-examples) ⏭️  https://github.com/ansys/pymechanical-examples/pull/163
    - [x] [embedded](https://github.com/ansys/pymechanical-embedding-examples) ⏭️ ansys/pymechanical-embedding-examples#143

- [x] Update cheat sheet ⏭️ ansys/pyansys-cheat-sheet#68

**Comment by klmcadams** [comment]
All tasks have been completed
