### ISSUE TITLE
PyMech logo difficult to see in dark mode

### ISSUE THREAD

**Issue by klmcadams** [ansys/pymechanical#600]
In dark mode on GitHub, the PyMechanical logo in the README is difficult to see. Let's make a dark mode logo to fix this.

URL: https://mechanical.docs.pyansys.com/version/dev/index.html

![darkmode_logo](https://github.com/ansys/pymechanical/assets/58492561/85854847-456a-4210-af54-c44416bd09ae)

**Comment by RobPasMue** [comment]
I completely agree
