### ISSUE TITLE
Bug: Protobuf incompatible issue

### ISSUE THREAD

**Issue by dipinknair** [ansys/pymechanical#684]
PyMechanical does not have upper limit on probuf which creates issue in python3.9 where 5.26.1 is getting installed hence creating issue when installing other dependencies such as `ansys-api-mechanical` and `ansys-api-platform-instancemanagement`

**Comment by RobPasMue** [comment]
For some reason, the dependency resolution on 3.9 seems to be failing... It should detect that second level deps are defining upper limits on the protobuf version but it isn't... you have to actively specify it when installing ansys-mechanical-core

``pip install ansys-mechanical-core "protobuf<5"``
