### ISSUE TITLE
Add `ansys-tools-visualization-interface` for plotting

### ISSUE THREAD

**Issue by dipinknair** [ansys/pymechanical#781]
### 📝 Description of the feature

[ansys-tools-visualization-interface](https://github.com/ansys/ansys-tools-visualization-interface) provides an interface between PyAnsys libraries and different plotting backends.

### 🔗 Useful links and references

https://visualization-interface.tools.docs.pyansys.com/version/stable/index.html

**Comment by RobPasMue** [comment]
@AlejandroFernandezLuces - please help @dipinknair out as needed. This project should be easy to integrate on
