### ISSUE TITLE
Change production version to 2024R2

### ISSUE THREAD

**Issue by koubaa** [ansys/pymechanical#808]
2024R2 is out on the customer portal

**Comment by dipinknair** [comment]
- [ ] CI/CD
    - [ ] Update for 24R2 and developer version for nightly
    - [ ] Update examples repo cicd 
- [ ] Docker 
- [ ] Documentation
    - [ ] Drop 23R1 support
- [ ] Examples 
    - [ ] Embedding
    - [ ] Remote
- [ ] Update cheat sheet
