### ISSUE TITLE
[Embedding] Debugging with vscode in linux

### ISSUE THREAD

**Issue by dipinknair** [ansys/pymechanical#867]
Since embedding on Linux uses mechanical-env, which sets environment variables, it makes difficult to debug pymechanical scripts with vscode.

**Comment by dipinknair** [comment]
Instruction to debug pymechanical scripts using vscode in Linux

Create ``launch.json`` under ``.vscode``

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "envFile": "${workspaceFolder}/.vscode/.env"
        },
    ]
}
```
store all necessary env required in ``.env`` file under ``.vscode`` by doing 

```shell
mechanical-env env > .vscode/.env
```
Use Debug using launch.json and select ``launch.json`` file created under ``.vscode`` folder
![image](https://github.com/user-attachments/assets/f8cc4238-9eb4-4b44-8eaa-6d7601d4a260)

**Comment by rajesh1359** [comment]
Thanks @dipinknair . This works as expected.

**Comment by RobPasMue** [comment]
Closing since solved
